Repository ansys/pydpf-post, pull requests merged in 2022-09, with the labels that each got.

#148 Add a retro-compatibility check
  .github/workflows/ci.yml
Labels: CI/CD

#156 Bump to 0.2.6dev0
  pyproject.toml
Labels: maintenance

#164 Improve TypeHints
  docs/source/conf.py
  requirements/requirements_docs.txt
Labels: documentation
