Repository ansys/pydpf-post, pull requests merged in 2023-08, with the labels that each got.

#449 Remove rogue prints from tests
  tests/test_fluid_simulation.py
  tests/test_mesh_info.py
  tests/test_selection.py
Labels: CI/CD

#454 Fix incompatibility with PyVista>=0.40.0
  docs/source/conf.py
  pyproject.toml
  requirements/requirements_docs.txt
  requirements/requirements_test.txt
Labels: bug, dependencies

#455 Update compatibility table for 0.5.0
  docs/source/getting_started/compatibility.rst
Labels: documentation

#457 Bump to 0.5.1.dev0
  pyproject.toml
Labels: maintenance

#460 Bump dev requirements_dev.txt
  requirements/requirements_dev.txt
Labels: dependencies

#462 Implement request of fluid results using faces
  src/ansys/dpf/post/fluid_simulation.py
  tests/conftest.py
  tests/test_fluid_simulation.py
Labels: enhancement

#459 Fix doc release
  .github/workflows/ci.yml
  .github/workflows/ci_release.yml
  .github/workflows/docs.yml
  .github/workflows/releaser.yml
Labels: bug, CI/CD

#468 Add cheat sheet links in PyDPF-Core doc
  README.md
  docs/source/index.rst
Labels: documentation
