Repository ansys/pydpf-post, pull requests merged in 2023-03, with the labels that each got.

#296 Post refactor dataframe
  src/ansys/dpf/post/__init__.py
  src/ansys/dpf/post/data_object.py
  src/ansys/dpf/post/dataframe.py
  src/ansys/dpf/post/examples/__init__.py
  src/ansys/dpf/post/harmonic_mechanical_simulation.py
  src/ansys/dpf/post/index.py
  src/ansys/dpf/post/mesh.py
  src/ansys/dpf/post/modal_mechanical_simulation.py
  src/ansys/dpf/post/simulation.py
  src/ansys/dpf/post/static_mechanical_simulation.py
  src/ansys/dpf/post/transient_mechanical_simulation.py
  tests/conftest.py
  tests/test_dataframe.py
  tests/test_mesh.py
  tests/test_simulation.py
Labels: enhancement

#300 Create examples for pydpf-post and make small bug fixes
  examples/00-Different-analysis-types/01-static-simulation.py
  examples/00-Different-analysis-types/02-modal-simulation.py
  examples/00-Different-analysis-types/03-transient-simulation.py
  examples/00-Different-analysis-types/04-harmonic-complex-results.py
  examples/00-Different-analysis-types/README.txt
  examples/00-Overview/README.txt
  examples/01-Different-analysis-types/README.txt
  examples/02-Detailed-Examples/01-named-selections-modal-simulation.py
  examples/02-Detailed-Examples/02-modal-extract-sub-results.py
  examples/02-Detailed-Examples/03-explore-result-data-harmonic.py
  examples/02-Detailed-Examples/04-invariants.py
  examples/04-Legacy/00-overview_example.py
  examples/04-Legacy/01-get_data_from_static_simulation.py
  examples/04-Legacy/01-introduction.py
  examples/04-Legacy/02-static-analysis.py
  examples/04-Legacy/03-modal-analysis.py
  examples/04-Legacy/04-harmonic-analysis.py
  examples/04-Legacy/05-transient-analysis.py
  examples/04-Legacy/06-complex_results.py
  examples/04-Legacy/07-result_keywords.py
  examples/04-Legacy/08-result_on_path_of_coordinates.py
  examples/04-Legacy/09-basics.py
  pyproject.toml
  requirements/requirements_docs.txt
  requirements/requirements_test.txt
  src/ansys/dpf/post/__init__.py
  src/ansys/dpf/post/common.py
  src/ansys/dpf/post/dataframe.py
  src/ansys/dpf/post/examples/__init__.py
  src/ansys/dpf/post/index.py
  src/ansys/dpf/post/post_utility.py
  src/ansys/dpf/post/selection.py
  src/ansys/dpf/post/simulation.py
  tests/conftest.py
  tests/test_dataframe.py
  tests/test_simulation.py
Labels: bug, documentation

#307 Fix select on both component and mesh entities
  src/ansys/dpf/post/dataframe.py
Labels: bug

#306 Add Dataframe.array
  examples/02-Detailed-Examples/05-export_data.py
  src/ansys/dpf/post/dataframe.py
  tests/test_dataframe.py
Labels: enhancement

#309 Add an associated displacement workflow to a DataFrame
  src/ansys/dpf/post/__init__.py
  src/ansys/dpf/post/dataframe.py
  src/ansys/dpf/post/harmonic_mechanical_simulation.py
  src/ansys/dpf/post/modal_mechanical_simulation.py
  src/ansys/dpf/post/simulation.py
  src/ansys/dpf/post/static_mechanical_simulation.py
  src/ansys/dpf/post/transient_mechanical_simulation.py
  tests/test_dataframe.py
Labels: enhancement

#281 Update install commands
  docs/source/_templates/sidebar-nav-bs.html
  docs/source/getting_started/install.rst
Labels: documentation

#316 Last improvements to documentation for 0.3.0
  .github/workflows/docs.yml
  README.md
  docs/source/conf.py
  docs/source/contributing.rst
  docs/source/getting_started/index.rst
  docs/source/getting_started/install.rst
  docs/source/images/crankshaft_stress_xx.png
  docs/source/index.rst
  docs/source/user_guide/accessing_file_metadata.rst
  docs/source/user_guide/accessing_results.rst
  docs/source/user_guide/extending_to_core.rst
  docs/source/user_guide/index.rst
  docs/source/user_guide/plotting.rst
  docs/source/user_guide/post_processing.rst
  docs/source/user_guide/troubleshooting.rst
  examples/02-Legacy/00-overview_example.py
  examples/02-Legacy/01-introduction.py
  examples/02-Legacy/02-static-analysis.py
  examples/02-Legacy/03-modal-analysis.py
  examples/02-Legacy/04-harmonic-analysis.py
  examples/02-Legacy/05-transient-analysis.py
  examples/02-Legacy/README.txt
  pyproject.toml
  run_client.bat
  src/ansys/dpf/post/common.py
  src/ansys/dpf/post/dataframe.py
  src/ansys/dpf/post/examples/__init__.py
  src/ansys/dpf/post/harmonic_mechanical_simulation.py
  src/ansys/dpf/post/index.py
  src/ansys/dpf/post/mesh.py
  src/ansys/dpf/post/misc.py
  src/ansys/dpf/post/modal_mechanical_simulation.py
  src/ansys/dpf/post/post_utility.py
  src/ansys/dpf/post/selection.py
  src/ansys/dpf/post/simulation.py
  src/ansys/dpf/post/static_mechanical_simulation.py
  src/ansys/dpf/post/transient_mechanical_simulation.py
  tests/test_load_simulation.py
Labels: documentation

#317 Vale: accept "PyDPF-Core"
  docs/styles/Vocab/ANSYS/accept.txt
Labels: CI/CD

#318 Fix calls to doc deployment actions
  .github/workflows/ci.yml
  .github/workflows/ci_release.yml
  .github/workflows/releaser.yml
Labels: CI/CD

#319 Fix doc deployment 2
  .github/workflows/ci.yml
  .github/workflows/docs.yml
  .github/workflows/releaser.yml
Labels: CI/CD

#326 Bump to 0.3.1.dev0
  pyproject.toml
Labels: maintenance

#325 Fix switcher in documentation build script
  .github/workflows/releaser.yml
  docs/source/conf.py
Labels: documentation

#329 Update license file year
  LICENSE
Labels: maintenance

#328 Improvements to pyproject.toml - contact email
  pyproject.toml
Labels: CI/CD

#332 Fix pandas pinned version for 3.7
  requirements/requirements_test.txt
Labels: CI/CD

#330 Add units to ResultsIndex
  src/ansys/dpf/post/index.py
  src/ansys/dpf/post/simulation.py
  tests/test_dataframe.py
  tests/test_index.py
Labels: enhancement

#350 Fix call to doc-deploy-stable
  .github/workflows/releaser.yml
Labels: CI/CD
