Repository ansys/pydpf-post, pull requests merged in 2023-04, with the labels that each got.

#345 Propagate Premium ServerContext as default
  .github/workflows/docs.yml
  docs/source/user_guide/server_context.rst
  examples/02-Legacy/08-result_on_path_of_coordinates.py
  tests/conftest.py
Labels: enhancement

#333 Add DataFrame.min and DataFrame.max over 'set_ids' axis or MeshIndex
  .github/workflows/ci.yml
  .github/workflows/ci_release.yml
  examples/01-Detailed-Examples/06-compute-min-max.py
  src/ansys/dpf/post/dataframe.py
  tests/test_dataframe.py
Labels: enhancement

#354 Update compatibility.rst for DPF Server 2023.2.pre1
  docs/source/getting_started/compatibility.rst
Labels: documentation

#336 Expose arguments for cyclic result queries
  docs/source/conf.py
  examples/00-Different-analysis-types/01-static-simulation.py
  examples/01-Detailed-Examples/02-modal-extract-sub-results.py
  examples/01-Detailed-Examples/04-invariants.py
  examples/01-Detailed-Examples/06-cyclic-results.py
  examples/01-Detailed-Examples/07-multi-stage-cyclic-results.py
  requirements/requirements_test.txt
  src/ansys/dpf/post/dataframe.py
  src/ansys/dpf/post/harmonic_mechanical_simulation.py
  src/ansys/dpf/post/modal_mechanical_simulation.py
  src/ansys/dpf/post/simulation.py
  src/ansys/dpf/post/static_mechanical_simulation.py
  src/ansys/dpf/post/transient_mechanical_simulation.py
  tests/conftest.py
  tests/test_dataframe.py
  tests/test_simulation.py
Labels: enhancement

#353 Update issue templates
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/examples.yml
Labels: CI/CD

#358 Fix calls to doc-deploy-dev/stable pyansys actions
  .github/workflows/ci.yml
  .github/workflows/docs.yml
  .github/workflows/releaser.yml
Labels: CI/CD

#361 Fix dev doc upload
  .github/workflows/docs.yml
Labels: CI/CD

#362 Fix doc deployment
  .github/workflows/ci.yml
Labels: CI/CD

#363 Finalize fix to deploy-doc actions
  .github/workflows/ci.yml
  .github/workflows/docs.yml
  .github/workflows/releaser.yml
Labels: CI/CD

#360 Fix 03-explore-result-data-harmonic
  examples/01-Detailed-Examples/03-explore-result-data-harmonic.py
Labels: documentation

#369 Change email address and add info on switching doc versions
  README.md
  docs/source/contributing.rst
  docs/source/index.rst
Labels: documentation

#383 Fix issue in electric test
  tests/test_electricanalysis.py
Labels: bug
