Repository ansys/pydpf-post, pull requests merged in 2023-09, with the labels that each got.

#482 Update CI to handle refactor of ansys-dpf-core
  .github/workflows/ci.yml
  .github/workflows/docs.yml
  .github/workflows/examples.yml
  requirements/requirements_dev.txt
Labels: CI/CD

#484 Remove 221 from testing
  .github/workflows/ci.yml
  .github/workflows/ci_release.yml
Labels: CI/CD

#461 Add class signature type-hinting
  docs/source/conf.py
Labels: documentation

#486 Fix docs zipping
  .github/workflows/docs.yml
Labels: CI/CD

#483 StaticMechanicalSimulation.thermal_strain
  src/ansys/dpf/post/static_mechanical_simulation.py
  src/ansys/dpf/post/transient_mechanical_simulation.py
  tests/test_simulation.py
Labels: enhancement

#487 Implement and test flprj argument for FluidSimulation
  src/ansys/dpf/post/fluid_simulation.py
  tests/test_fluid_simulation.py
Labels: enhancement

#475 Do not package example files
  src/ansys/dpf/post/examples/__init__.py
Labels: maintenance

#480 Expose streamlines
  conftest.py
  src/ansys/dpf/post/examples/__init__.py
  src/ansys/dpf/post/helpers/__init__.py
  src/ansys/dpf/post/helpers/selections.py
  src/ansys/dpf/post/helpers/streamlines.py
  src/ansys/dpf/post/index.py
  src/ansys/dpf/post/simulation.py
  src/ansys/dpf/post/tools.py
  tests/test_dataframe.py
  tests/test_faces.py
  tests/test_fluid_simulation.py
  tests/test_load_simulation.py
  tests/test_mesh.py
  tests/test_mesh_info.py
  tests/test_named_selection.py
  tests/test_phase.py
  tests/test_selection.py
  tests/test_simulation.py
  tests/test_species.py
  tests/test_streamlines.py
Labels: enhancement

#497 Update for Euler angles result
  src/ansys/dpf/post/dpf_solution.py
  tests/test_simulation.py
Labels: enhancement

#498 Update HeatingCoil.res by CFF files
  tests/test_fluid_simulation.py
Labels: CI/CD
