Repository ansys/pydpf-post, pull requests merged in 2023-10, with the labels that each got.

#508 update docstring euler angles
  src/ansys/dpf/post/dpf_solution.py
Labels: CI/CD

#499 Fix results extraction for simulation object with given server
  src/ansys/dpf/post/harmonic_mechanical_simulation.py
  src/ansys/dpf/post/simulation.py
  tests/test_simulation.py
Labels: bug

#511 Vale ignore RST roles
  docs/.vale.ini
Labels: CI/CD

#514 Correct values to account for the issue in the mesh_skin operator
  tests/test_simulation.py
Labels: bug

#515 Update supported Python versions
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/examples.yml
  .github/workflows/ci.yml
  .github/workflows/ci_release.yml
  .github/workflows/docs.yml
  .github/workflows/releaser.yml
  pyproject.toml
Labels: CI/CD, dependencies

#516 Remove Vale Google.Headings warnings due to false positives
  .pre-commit-config.yaml
  docs/.vale.ini
  docs/source/user_guide/accessing_results.rst
  docs/styles/Vocab/ANSYS/accept.txt
Labels: CI/CD

#521 Fix call to docs job in ci_release.yml
  .github/workflows/ci_release.yml
Labels: CI/CD

#522 Revert docstring to conform to DPF 2024.1.pre0
  src/ansys/dpf/post/dpf_solution.py
Labels: CI/CD

#523 Fix condition on server version in test_simulation_results
  tests/test_simulation.py
Labels: CI/CD

#519 Clean init file
  src/ansys/dpf/post/__init__.py
Labels: maintenance

#526 Fix Vale accept
  docs/.vale.ini
  docs/source/user_guide/known_issues_list.rst
  docs/styles/Vocab/ANSYS/accept.txt
Labels: CI/CD

#527 Bump to 0.6.1.dev0
  pyproject.toml
Labels: maintenance
