Repository ansys/pydpf-post, pull requests merged in 2024-11, with the labels that each got.

#745 Update for numpy 2
  src/ansys/dpf/post/mesh_info.py
Labels: bug

#754 Fix releaser getting the latest release tag to download artifacts from
  .github/workflows/releaser.yml
Labels: CI/CD

#755 Bump 0.9.3.dev0
  pyproject.toml
Labels: maintenance

#757 Target 25.2 in ci
  .github/workflows/ci.yml
  .github/workflows/docs.yml
  .github/workflows/examples.yml
Labels: CI/CD

#613 Fix DataFrame.select when no set index
  src/ansys/dpf/post/dataframe.py
  src/ansys/dpf/post/index.py
  tests/test_dataframe.py
Labels: bug

#762 Pin down vtk to 9.3.1
  requirements/requirements_docs.txt
  requirements/requirements_test.txt
Labels: CI/CD, dependencies
